#!/bin/bash

# Aggiorna il percorso alla tua versione di CPLEX
export CPLEX="/opt/ibm/ILOG/CPLEX_Studio2211/cplex/lib/x86-64_linux/static_pic/libcplex.a"

if [ ! -e "$CPLEX" ]; then
    echo "$CPLEX is not the libcplex.a library file"
    exit 1
fi

# Aggiorna il percorso per libilocplex.a
export ILOCPLEX="/opt/ibm/ILOG/CPLEX_Studio2211/cplex/lib/x86-64_linux/static_pic/libilocplex.a"

if [ ! -e "$ILOCPLEX" ]; then
    echo "$ILOCPLEX is not the libilocplex.a library file"
    exit 1
fi

# Aggiorna il percorso per libconcert.a
export CONCERT="/opt/ibm/ILOG/CPLEX_Studio2211/concert/lib/x86-64_linux/static_pic/libconcert.a"

if [ ! -e "$CONCERT" ]; then
    echo "$CONCERT is not the libconcert.a library file"
    exit 1
fi

# Aggiorna il percorso agli include di CPLEX
export CPLEX_INCLUDES="/opt/ibm/ILOG/CPLEX_Studio2211/cplex/include"

if [ ! -e "$CPLEX_INCLUDES/ilcplex/ilocplex.h" ]; then
    echo "$CPLEX_INCLUDES does not point to a path containing ilcplex/ilocplex.h"
    exit 1
fi

# Aggiorna il percorso agli include di Concert
export CONCERT_INCLUDES="/opt/ibm/ILOG/CPLEX_Studio2211/concert/include"

if [ ! -e "$CONCERT_INCLUDES/ilconcert/iloenv.h" ]; then
    echo "$CONCERT_INCLUDES does not point to a path containing ilconcert/iloenv.h"
    exit 1
fi

cd static
cmake -DCMAKE_VERBOSE_MAKEFILE=TRUE -DSTATIC_OPTIC=TRUE -DCMAKE_BUILD_TYPE=Release -DCPLEX="$CPLEX" -DILOCPLEX="$ILOCPLEX" -DCONCERT="$CONCERT" -DCPLEX_INCLUDES="$CPLEX_INCLUDES" -DCONCERT_INCLUDES="$CONCERT_INCLUDES" ../src

